[build.environment]
  NODE_VERSION = "18.8.0"
  YARN_VERSION = "1.22.19"

[build]
  command = "yarn build"
  publish = "public/"

[dev]
  command = "yarn start"
  publish = "public/"
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/effection/:splat"
